### ISSUE TITLE
Can't get SIWE to work with brave during development

### ISSUE THREAD

**Issue by joewagner** [spruceid/siwe-quickstart#40]
I ran into an issue doing some QA testing of our site while using the Brave browser.  If I run a localhost dev network and app, I can't sign-in.  I'm getting the following error:

```
http://localhost:8080
We've rejected this request because this site is requesting that you use a different domain (https://localhost:8080)
```

Note that The brave browser thinks the site is requesting that I use https, when the site is using http.  If I change the [`domain` property of the SIWE object](https://github.com/spruceid/siwe-quickstart/blob/main/03_complete_app/frontend/src/index.js#L4) to the fully qualified origin, the Brave wallet will sign the message but the backend will not verify the message.

To debug I tried using some of the apps in this repo, but they don't seem to work with Brave either. 

To reproduce start up the quickstart `03_complete_app`, and try to sign-in with Brave.  

fwiw: everything works as expected on a public https domain.

**Comment by sbihel** [comment]
If the issue is really with the `domain` field, it means that the Brave wallet is somehow adding a default scheme but the scheme is optional. Maybe they do it for security purposes but it is a deviation from the specs.

As for why the backend is not successfully verifying the message, I suspect it's because it's using an older version of the `siwe` library, which doesn't have support for the optional scheme. A PR would be welcome to update it. (If you do update it, please note that scheme is its own field and shouldn't be part of `domain`)

**Comment by joewagner** [comment]
@sbihel Thanks for the response.
I'll bump the siwe version and see if that works, regardless I will work on a PR once I find a fix.
